name: Playwright Tests
on:
  push:
    branches: [ main ]

jobs:
  playwrighttests:
    runs-on: windows-latest
    env:
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}

    steps:
      - name: Install dependencies
        shell: bash
        run: |
          if [ -f package-lock.json ]; then
            echo "Using npm ci"
            npm ci
          elif [ -f yarn.lock ]; then
            echo "Using yarn install"
            yarn install --frozen-lockfile
          else
            echo "No lockfile found, running npm install"
            npm install
          fi

      - name: Start shopping store application
        run: ./shopping-store-windows-386.exe &

      - name: Run Playwright tests
        run: npm run test
