name: Playwright Tests
on:
  push:
    branches: [ main ]

jobs:
  playwrighttests:
    runs-on: windows-latest
    env:
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Start shopping store application
        run: ./shopping-store-windows-386.exe &

      - name: Run Playwright tests
        run: npm run test
